CLASS zz1_cl_wotype DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZZ1_I_WOTYPE.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_WOTYPE IMPLEMENTATION.
ENDCLASS.
