CLASS ZZ1_I_POHDMESLOG_LT DEFINITION INHERITING FROM cl_abap_behavior_handler.
  PRIVATE SECTION.

    METHODS get_global_authorizations FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST requested_authorizations FOR ZZ1_I_POHDMESLOG RESULT result.

ENDCLASS.

CLASS ZZ1_I_POHDMESLOG_LT IMPLEMENTATION.

  METHOD get_global_authorizations.
  ENDMETHOD.

ENDCLASS.
