CLASS zz1_cl_pohdmes DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zz1_i_pohdmes.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_POHDMES IMPLEMENTATION.
ENDCLASS.
