CLASS zz1_cl_pohdmeslog DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZZ1_I_POHDMESLOG.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_POHDMESLOG IMPLEMENTATION.
ENDCLASS.
